---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-telegraf
      vars:
        telegraf_outputs_influxdb:
          - host: 1.2.3.4
            port: 8086
            db_name: test
            retention_policy: "rp"
            user_name: "un"
            user_password: "up"
            namepass: ['np1', 'np2']
            namedrop: ['nd1', 'nd2']
          - host: 5.6.7.8
            port: 8086
            db_name: test2
            user_name: "un"
            user_password: "up"
